### ISSUE TITLE
404 error is coming 

### ISSUE THREAD

**Issue by maaixprt** [lamecksilva/CRUD#1]
localhost:9000/

server is running and db is also running

is giving this error:

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<title>Error</title>
</head>

<body>
	<pre>Cannot GET /</pre>
</body>

</html>

**Comment by maaixprt** [comment]
Here are docker logs: 
```

$ docker logs NODEJS_SERVER -f
[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node index.js server.js`
Server running on 9000
{ MongoNetworkError: failed to connect to server [192.168.38.129:27027] on first connect [MongoNetworkError: connect EHOSTUNREACH 192.168.38.129:27027]
    at Pool.<anonymous> (/node-app/node_modules/mongodb-core/lib/topologies/server.js:564:11)
    at Pool.emit (events.js:193:13)
    at Connection.<anonymous> (/node-app/node_modules/mongodb-core/lib/connection/pool.js:317:12)
    at Object.onceWrapper (events.js:281:20)
    at Connection.emit (events.js:193:13)
    at Socket.<anonymous> (/node-app/node_modules/mongodb-core/lib/connection/connection.js:246:50)
    at Object.onceWrapper (events.js:281:20)
    at Socket.emit (events.js:193:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {} }
[nodemon] restarting due to changes...
[nodemon] starting `node index.js server.js`
Server running on 9000
MongoDB connected

```
